# Generated by Django 2.2.4 on 2019-09-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='group',
            field=models.CharField(choices=[('EE', 'Eastern Empids')], max_length=1),
        ),
        migrations.AlterField(
            model_name='bird',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
