# Generated by Django 2.2.4 on 2019-09-10 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190909_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bird',
            name='deactivated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
