# Generated by Django 2.2.4 on 2019-09-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190911_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
