# Generated by Django 2.2.4 on 2019-09-12 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_guess_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='bird',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='core.Bird'),
        ),
        migrations.AlterUniqueTogether(
            name='guess',
            unique_together={('bird', 'user')},
        ),
    ]
